### ISSUE TITLE
radio-cardをtabで操作できるようにする

### ISSUE THREAD

**Issue by kanaru-ssk** [kanaru-ssk/next-stepper-form#2]
## 概要

tabキーでフォーカスが当たり、スペースキーで選択できるようにする。

**Comment by yui-szk** [comment]
ラジオボタンの選択するのが1つだけという性質のため、
- tabキーでラジオボタングループにフォーカス
- 十字キーで選択
- 選択後tabキーで次へ/決定ボタンにフォーカス
という形で実装するのがいいかなと思っていましたがいかがでしょう

**Comment by kanaru-ssk** [comment]
@yui-szk なるほど！確かに普通にradio実装したらそういう動きになってた。

じゃあこれは出来てるね。

そしたら、tabキーでcardそれぞれにもfocusあたっちゃうのを解消してほしい :pray:

**Comment by kanaru-ssk** [comment]
別issueにしたのでこっちはcloseします

**Comment by yui-szk** [comment]
> @yui-szk なるほど！確かに普通にradio実装したらそういう動きになってた。
> 
> じゃあこれは出来てるね。
> 
> そしたら、tabキーでcardそれぞれにもfocusあたっちゃうのを解消してほしい 🙏

ローカルの方で修正してたのであとでプッシュしておきますー
